### ISSUE TITLE
Range of the first type is in the range of the latter.

### ISSUE THREAD

**Issue by shogutest** [coffeina/Madagaskar#3]
Having regard to the above point beforehand warn there is no need to convert the value of type int WiekUzytkownia it - nothing stands in the way to subtract a byte of int because both types are numeric types, total, and the range of the first type is in the range of the latter .

**Comment by coffeina** [comment]
Fixed. 
Console.WriteLine("Cześć! Urodziłeś się w " + (Convert.ToInt32(DateTime.Now.Year) - Convert.ToByte(Console.ReadLine())));
